generate: 1

solvers:
# - EULER
- DDIM
# - DDIMHF
- DPMS
# - DPMS3
# - DPMSORIG
- DEIS
# - DEIS3
- UNIPC
# - UNIPC3
# - POLS

schedulers:
# - DDIM
- LINEAR
- AYS
- KARRAS
- SNR

cachers_quantizers:
- NONE
# - DEEPCACHE
# - TGATE
# - FREEU
# - HQQ4
# - HQQ3

nfes:
# - 5
- 6
# - 7
- 8
- 9
# - 10
- 11
- 12
# - 17
# - 25
# - 50
# - 100

datasets:
- COCO
# - PARTI