generate: 1

solvers:
# - EULER
- DDIM
# - DDIMHF
- DPMS
# - DPMS3
# - DPMSORIG
# - DEIS
# - DEIS3
# - UNIPC
# - UNIPC3
# - IPNDM

schedulers:
# - DDIM
- LINEAR
# - AYS
# - KARRAS
# - SNR

cachers_quantizers:
- NONE
# - DEEPCACHE
# - TGATE
# - FREEU
# - HQQ4
# - HQQ3

nfes:
# - 5
# - 7
- 10
# - 17
# - 25
# - 50
# - 100

datasets:
- COCO
# - PARTI