solvers:
- DDIM
# - DPMS
# - DEIS
# - IPNDM
# - POLS
# - LIN

schedulers:
# - CUSTOM
- LINEAR
# - AYS
# - KARRAS
# - SNR

model_names:
- BASE
# - DEEPCACHE
# - HQQ
# - VQDM
# - EDM

nfes:
# - 5
# - 6
# - 7
# - 8
# - 9
# - 10
# - 11
# - 12
# - 17
# - 25
# - 50
# - 100
- 200

datasets:
- COCO
# - PARTI
# - CIFAR

metrics: # non-grid
- SEC_PER_IMG
- LPIPS
- FID
- IS
- CLIP
# - CIFAR_FID
# - TFLOPS
