
nfe: 5
loss: LATENT-L1
model: SD15_TRAIN
calc_metrics_epoch: 1
img_log_interval: 1
epochs: 400

solver:
  teacher: UNIPC2H__10
  init: DDIM
  lr: 0.001
  solver: COEFEXT2
  train: true

adv:
  lr: 0.001
  lambda: 2
  gamma: 0.2
  path: ''
  freeze: false
  recon_type: LL1

timesteps:
  lr: 0.001
  train: true
  start_method: linear
  param_method: cumprod

unet_timesteps:
  lr: 0.001
  train: true

dataset:
  train_size: 1000
  batch_size: 40
  mini_batch_size: 10
  val_size: 100
  val_batch_size: 1
  path: /workspace-SR008.fs2/philurame/DIFFUSION_SPEEDUP/DATA/TRAIN_DATA