name: null
project: "thecrazymage/reinforce-cacher"

model_name: "REINFORCE_CACHER"
metric: "patched-lpips"
solver: "DDIM"
scheduler: "LINEAR"
baseline_name: "DEEPCACHE3"

epochs: 300
train_batch_size: 8
val_batch_size: 8
max_samples: 64

gs: 5
teacher_nfe: 25
student_nfe: 25
num_steps: 9
num_samples: 2
eval_freq: 10

lr: 0.03
gamma: 1 # we don't need scheduler for now
same_train_noise: True
init_logits: "deepcache-3"