nfe: 7
model: SORA
epochs: 400
img_log_interval: 1

loss: 
  name: IQ-AQ-MS
  coeffs: [1,1,1]

metric:
  name: 
  period: 0

rl:
  num_samples: 2
  solver_sigma: -4
  lr: 0.01
  clip_grad_norm: 1

solver:
  train: false
  teacher: DDIM_LEADING_100_SHIFTED
  guide: null
  solver: DPMS
  lr: 0.01
  clip_grad_norm: 1

timesteps:
  train: true
  init_method: leading
  param_method: cumprod
  lr: 0.01
  clip_grad_norm: 1

dataset:
  train_size: 3
  batch_size: 2
  mini_batch_size: 1
  val_size: 2
  path: /workspace-SR008.fs2/philurame/DIFFUSION_SPEEDUP/DATA/TRAIN_DATA



# nfe: 10
# model: SD15
# epochs: 400
# img_log_interval: 1

# loss: 
#   name: L1
#   coeffs: [1,1,1]

# metric:
#   name: VBENCH
#   period: 0

# rl:
#   num_samples: 2
#   solver_sigma: -3
#   lr: 0.01
#   clip_grad_norm: 1

# solver:
#   train: true
#   teacher: DDIM_100
#   guide: DPMS
#   solver: COEF
#   lr: 0.01
#   clip_grad_norm: 1

# timesteps:
#   train: true
#   init_method: leading
#   param_method: cumprod
#   lr: 0.01
#   clip_grad_norm: 1

# dataset:
#   train_size: 1000
#   batch_size: 10
#   mini_batch_size: 1
#   val_size: 100
#   val_batch_size: 1
#   path: /workspace-SR008.fs2/philurame/DIFFUSION_SPEEDUP/DATA/TRAIN_DATA
