name: null

model_name: "REINFORCE_CACHER"
solver: "DDIM"
scheduler: "LINEAR"

epochs: 300
batch_size: 8
max_samples: 64
test_size: 1000
shuffle: True

gs: 5
teacher_nfe: 13
student_nfe: 13
num_steps: 4
num_samples: 6

alpha: 0.05                         # regularization for entropy
warming_entropy_epochs: 200        # how many epochs we use entropy regularizer 

logits_lr: 0.03
model_lr: 0
gamma: 1                       # we don't need scheduler for now
same_train_noise: True
ema_decay: 0.9

metric: "plpips_hps"
alpha_plpips: 1
alpha_hps: 3

logging:
  eval_freq: 10
  test_freq: 100
  display_k: 4
  validation: "deepcache-3"

logit_predictor:
  model_variant: constant
  train_logits: True
  
  init_logits: "deepcache-4"
  baseline_stride: 4