model_names:
# - SDXL_BASE
# - SD14_BASE
# - SD15_BASE
- SORA_BASE
# - DEEPCACHE2
# - DEEPCACHE3
# - DEEPCACHE4
# - HQQ
# - VQDM

solvers:
- DDIM
# - DPMS
# - DPMS3
# - DEIS
# - IPNDM2
# - IPNDM3
# - IPNDM4

# - UNIPC2
# - UNIPC2_
# - UNIPC2H
# - UNIPC2H_

# - UNIPC
# - UNIPC3_
# - UNIPC3H
# - UNIPC3H_



# - DEIS
# - COEF
# - COEFEXT
# - COEFEXT2
# - COEFEXTF
# - TCOEFUP*4|1

schedulers:
# - CUSTOM
- GITS
- LINEAR
- AYS
- KARRAS
- SNR

# - TDEIS
# - TCOEF
# - TCOEFEXT
# - TCOEFEXT2
# - TCOEFEXTF
# - TCOEFUP*4|1
# - TUCOEFEXT
# - TUCOEFEXT2

solvers_schedulers_nfes:
# - DEIS_LINEAR_4
# - COEF_TCOEF_4
# - DEIS_TDEIS_4
# - COEF41UP_TCOEF41UP_4
# - COEFEXT_TCOEFEXT_4
# - COEFEXT2_TCOEFEXT2_4
# - COEFEXTF_TCOEFEXTF_4
# - COEFEXT_TUCOEFEXT_4
# - COEFEXT2_TUCOEFEXT2_4

# - DEIS_TDEIS_6
# - DEIS_LINEAR_6
# - COEFEXT2_TUCOEFEXT2_6
# - COEF41UP_COEF41UP_6

# - DEIS_LINEAR_10
# - COEF_TCOEF_10
# - DEIS_TDEIS_10
# - COEF41UP_TCOEF41UP_10
# - COEFEXT_TCOEFEXT_10
# - COEFEXT2_TCOEFEXT2_10
# - COEFEXTF_TCOEFEXTF_10
# - COEFEXT_TUCOEFEXT_10
# - COEF41UP_COEF41UP_10
# - COEFEXT2_TUCOEFEXT2_10

nfes:
# - 3
# - 4
# - 5
# - 6
# - 7
# - 8
# - 9
- 10
# - 11
# - 12
# - 13
# - 14
# - 15
# - 17
- 20
# - 25
- 35
# - 40
- 50
- 75
# - 60
- 100
# - 200

datasets:
# - COCO
# - COCO30
# - NEWCOCO30
# - COCOLD3
# - PARTI
- HUAWEI


metrics: # non-grid
# - SEC_PER_IMG
# - LPIPS
# - FID2-REFS
# - FID2-IMGS
# - FID1
# - FID
# - IS
# - CLIP
# - CIFAR_FID
# - TFLOPS