model_names:
# - SDXL_BASE
# - SD14_BASE
- SD15_BASE
# - DEEPCACHE2
# - DEEPCACHE3
# - DEEPCACHE4
# - HQQ
# - VQDM

solvers:
# - DDIM
- DPMS
- DPMS3
- IPNDM3
# - POLS

# - DEIS
# - COEF
# - COEFEXT
# - COEFEXT2
# - COEFEXTF
# - TCOEFUP*4|1

schedulers:
# - CUSTOM
- LINEAR
# - AYS
# - KARRAS
# - SNR

# - TDEIS
# - TCOEF
# - TCOEFEXT
# - TCOEFEXT2
# - TCOEFEXTF
# - TCOEFUP*4|1
# - TUCOEFEXT
# - TUCOEFEXT2

solvers_schedulers_nfes:
# - DEIS_LINEAR_4
# - COEF_TCOEF_4
# - DEIS_TDEIS_4
# - COEF41UP_TCOEF41UP_4
# - COEFEXT_TCOEFEXT_4
# - COEFEXT2_TCOEFEXT2_4
# - COEFEXTF_TCOEFEXTF_4
# - COEFEXT_TUCOEFEXT_4
# - COEFEXT2_TUCOEFEXT2_4

# - DEIS_TDEIS_6
# - DEIS_LINEAR_6
# - COEFEXT2_TUCOEFEXT2_6
# - COEF41UP_COEF41UP_6

# - DEIS_LINEAR_10
# - COEF_TCOEF_10
# - DEIS_TDEIS_10
# - COEF41UP_TCOEF41UP_10
# - COEFEXT_TCOEFEXT_10
# - COEFEXT2_TCOEFEXT2_10
# - COEFEXTF_TCOEFEXTF_10
# - COEFEXT_TUCOEFEXT_10
# - COEF41UP_COEF41UP_10
# - COEFEXT2_TUCOEFEXT2_10


# - DPMS3_LINEAR_6
# - DPMS3_LINEAR_10
# - IPNDM_LINEAR_6
# - IPNDM_LINEAR_10

# - UNIPC2_LINEAR_10
# - UNIPC3_LINEAR_6
# - UNIPC3_LINEAR_10
# - IPNDM_LINEAR_4
# - IPNDM_LINEAR_6
# - IPNDM_LINEAR_10

# - UNIPC2_LINEAR_6
# - UNIPC2_LINEAR_10
# - UNIPC3_LINEAR_6
# - UNIPC3_LINEAR_10
# - IPNDM_LINEAR_4
# - IPNDM_LINEAR_6
# - IPNDM_LINEAR_10

nfes:
- 4
# - 5
- 6
# - 7
- 8
# - 9
# - 10
# - 11
# - 12
# - 13
# - 14
# - 17
# - 20
# - 25
# - 30
# - 40
# - 50
# - 60
# - 100
# - 200

datasets:
# - COCO
- COCO30
# - PARTI


metrics: # non-grid
# - SEC_PER_IMG
# - LPIPS
- FID1
- FID
- IS
- CLIP
# - CIFAR_FID
# - TFLOPS
